#!/bin/bash

[ $1 == "up" ] && pactl set-sink-volume @DEFAULT_SINK@ +5%
[ $1 == "down" ] && pactl set-sink-volume @DEFAULT_SINK@ -5%
[ $1 == "mute" ] && pactl set-sink-mute @DEFAULT_SINK@ toggle
current_volume=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5}' | sed 's/%//')
mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')

[ $1 == "init" ] && echo $current_volume >~/.config/river/tmp/volume.txt

[ $mute == "yes" ] && echo X >>~/.config/river/tmp/volume.txt || echo $current_volume >>~/.config/river/tmp/volume.txt
